name: ❓ Miscellaneous
description: Use this for any other issues. Do NOT create blank issues.
labels: [pending triage]
body:
  - type: textarea
    id: description
    attributes:
      label: Description of the issue.
      description: Provide a clear and concise explanation of your issue.
    validations:
      required: true
  - type: textarea
    id: extra_information
    attributes:
      label: Additional information
      description: Is there anything else we should know about this issue?
  - type: checkboxes
    id: checkboxes
    attributes:
      label: Validations
      description: Before submitting the issue, please make sure you do the following
      options:
        - label: Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
          required: true
        - label: Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
          required: true
        - label: Read the [docs](https://vitest.dev/guide/).
          required: true
        - label: Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
          required: true
